### ISSUE TITLE
Fails for Python 2 

### ISSUE THREAD

**Issue by fangohr** [joommf/joommfutil#2]
Now that we value the exit value of tests in the conda builds, I have noticed that all the python 2.7 builds fail for joommfutil. Here is the windows output:
https://ci.appveyor.com/project/conda-forge/joommfutil-feedstock/build/1.0.8

I would guess that we never intended for this to work for Python 2, and as other parts of JOOMMF do depend on python 3, I will just mark the conda recipes to not build for Python 2.

@marijanbeg - please complain if this is wrong.

**Comment by marijanbeg** [comment]
Yes, that is right. JOOMMF is intended to work only with Python 3.6+.
